import "./globals.css";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "ai note",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <div className="h-8" data-testid="header">
          header
        </div>
        {children}
      </body>
    </html>
  );
}
