name: Deploy Vercel

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - main
    types: [closed]

jobs:
  deployment:
    name: Deploy
    runs-on: ubuntu-latest
    environment: |-
      if [ "${GITHUB_REF##*/}" = "main" ]; then
        Production;
      else
        Preview;
      fi
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      # - name: Test
      #   run: |-
      #     npm install
      #     npm run test
      - name: Deploy
        run: |-
          if [ "${GITHUB_REF##*/}" = "develop" ]; then
            curl ${{ secrets.VERCEL_DEVELOP_HOOKS }};
          elif [ "${GITHUB_REF##*/}" = "main" ]; then
            curl ${{ secrets.VERCEL_MAIN_HOOKS }};
          fi
